apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: keepalived_patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- envs:
  - ironic_bmo_configmap.env
  behavior: merge
  name: ironic-bmo-configmap
